apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-audiobookshelf-metadata
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: NAS_IP_PLACEHOLDER
  share: /volume/NAS_DATA_PATH_PLACEHOLDER/audiobookshelf-metadata
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
  - nolock
  - async
  - hard
