apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-outline-postgres
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NAS_IP}
  share: /volume/NAS_DATA_PATH_PLACEHOLDER/outline-postgres
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
  - nolock
  - async
  - hard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-outline-data
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NAS_IP}
  share: /volume/NAS_DATA_PATH_PLACEHOLDER/outline-data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
  - nolock
  - async
  - hard
