apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: servarr-secrets
  namespace: servarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: servarr-secrets
  dataFrom:
    - extract:
        key: cflkpp43ba4c7du7b4kk2t3qmy  # servarr item in Server Infrastructure vault
