apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          env:
            - name: TZ
              value: Europe/Lisbon
            - name: LOG_LEVEL
              value: info
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: servarr
spec:
  selector:
    app: jellyseerr
  ports:
    - port: 5055
