apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage
  namespace: docmost
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-docmost
  resources:
    requests:
      storage: 20Gi
