apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: immich-secrets
  dataFrom:
    - extract:
        key: p62y4styzmxyxnnrg4nxxf2zpy  # Immich - talos-home in Server Infrastructure vault
        # Fields: POSTGRES_PASSWORD
