apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
  annotations:
    tailscale.com/funnel: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Immich"
    gethomepage.dev/description: "Photo library"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "immich"
    gethomepage.dev/href: "https://immich.${TAILNET_DOMAIN}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=server,app.kubernetes.io/instance=immich"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 2283
  tls:
    - hosts:
        - immich
