apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    template:
      data:
        admin-user: "admin"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: d2zm4smwn2xhvohjj5xupo2oxa  # Grafana - talos-home in Server Infrastructure vault
