apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-db-nfs
  namespace: wallos
spec:
  storageClassName: nfs-wallos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-uploads-nfs
  namespace: wallos
spec:
  storageClassName: nfs-wallos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallos
  namespace: wallos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallos
  template:
    metadata:
      labels:
        app: wallos
    spec:
      securityContext:
        runAsUser: 977
        runAsGroup: 988
        fsGroup: 988
      containers:
        - name: wallos
          image: bellamy/wallos:latest
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Europe/Lisbon
          volumeMounts:
            - name: db
              mountPath: /var/www/html/db
            - name: uploads
              mountPath: /var/www/html/images/uploads
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: wallos-db-nfs
        - name: uploads
          persistentVolumeClaim:
            claimName: wallos-uploads-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: wallos
  namespace: wallos
spec:
  selector:
    app: wallos
  ports:
    - port: 80
