apiVersion: v1
kind: PersistentVolume
metadata:
  name: actualbudget-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: ${NAS_DATA_PATH}/actual
  mountOptions:
    - nfsvers=3
    - nolock
    - async
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data
  namespace: actualbudget
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: actualbudget-data
  storageClassName: ""
