apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  # cluster-secret-store.yaml is applied by the flux/kustomizations/external-secrets-store.yaml
  # after the HelmRelease (CRDs) are ready, to avoid a race condition.
