apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
  namespace: ghostfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghostfolio
  template:
    metadata:
      labels:
        app: ghostfolio
    spec:
      containers:
        - name: ghostfolio
          image: ghostfolio/ghostfolio:latest
          ports:
            - containerPort: 3333
          env:
            - name: NODE_ENV
              value: production
            - name: ACCESS_TOKEN_SALT
              value: Hht7SThjPyq6oGd5Ms32qwnS5eIJP0kLnqlQu0wU
            - name: JWT_SECRET_KEY
              value: DfO0RA9FxTrQ5D23qc1oZgQcwMUGz3Pjk4TxtWSzgo
            - name: DATABASE_URL
              value: postgresql://ghostfolio:ghostfolio@ghostfolio-postgres:5432/ghostfolio
            - name: REDIS_HOST
              value: ghostfolio-redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio
  namespace: ghostfolio
spec:
  selector:
    app: ghostfolio
  ports:
    - port: 3333
