apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio-redis
  namespace: ghostfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghostfolio-redis
  template:
    metadata:
      labels:
        app: ghostfolio-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio-redis
  namespace: ghostfolio
spec:
  selector:
    app: ghostfolio-redis
  ports:
    - port: 6379
