apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account-token
          namespace: external-secrets
          key: token
