apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich/
  - adventurelog/
  - monitoring/
  - docmost/
  - actualbudget/
  - bentopdf/
  - wallos/
  - audiobookshelf/
  - watchyourlan/
  - homebox/
  - librespeed/
  - it-tools/
  - homarr/
