apiVersion: v1
kind: Service
metadata:
  name: gitea-tailscale
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh-tailscale
  namespace: gitea
  annotations:
    tailscale.com/hostname: "gitea-ssh"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: gitea
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
