apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventurelog-postgres-nfs
  namespace: adventurelog
spec:
  storageClassName: nfs-adventurelog-postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adventurelog-postgres
  namespace: adventurelog
spec:
  serviceName: adventurelog-postgres
  replicas: 1
  selector:
    matchLabels:
      app: adventurelog-postgres
  template:
    metadata:
      labels:
        app: adventurelog-postgres
    spec:
      securityContext:
        runAsUser: 977
        runAsGroup: 988
        fsGroup: 988
      containers:
        - name: postgres
          image: postgis/postgis:16-3.4
          env:
            - name: POSTGRES_DB
              value: adventurelog
            - name: POSTGRES_USER
              value: adventurelog
            - name: POSTGRES_PASSWORD
              value: adventurelog
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: adventurelog-postgres-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: adventurelog-postgres
  namespace: adventurelog
spec:
  selector:
    app: adventurelog-postgres
  ports:
    - port: 5432
