apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventurelog-media
  namespace: adventurelog
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-adventurelog
  resources:
    requests:
      storage: 50Gi
